"""empty message

Revision ID: 1baad451c0b8
Revises: 67e09144f4fb
Create Date: 2025-07-09 09:11:18.854117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1baad451c0b8'
down_revision: Union[str, None] = '67e09144f4fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('admins',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('tg_id', sa.BigInteger(), nullable=False),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    # ### end Alembic commands ###
