"""empty message

Revision ID: 5e26b8e3087d
Revises: a87d01fcb8f2
Create Date: 2025-07-11 10:22:18.354798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e26b8e3087d'
down_revision: Union[str, None] = 'a87d01fcb8f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'is_active')
    # ### end Alembic commands ###
