"""empty message

Revision ID: a87d01fcb8f2
Revises: 8195d51dbb83
Create Date: 2025-07-10 21:03:59.370243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a87d01fcb8f2'
down_revision: Union[str, None] = '8195d51dbb83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tariff_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_subscriptions_tariff_id_tariffs',  # Назови констрейнт явно
            'tariffs',
            ['tariff_id'],
            ['id']
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'tariff_id')
    # ### end Alembic commands ###
