"""empty message

Revision ID: eee6cbf2aa5b
Revises: cdeb11749683
Create Date: 2026-05-07 17:54:59.626967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eee6cbf2aa5b'
down_revision: Union[str, None] = 'cdeb11749683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('description', sa.String(), nullable=False))
    op.add_column('courses', sa.Column('video', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'video')
    op.drop_column('courses', 'description')
    # ### end Alembic commands ###
